name: llm
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scipy
  - pyyaml
  - pydantic
  - typing-extensions
  - python-dotenv
  - openai
  - google-genai
  - mistralai
  - together
  - matplotlib
  - scikit-learn
  - joblib
  - pip:
      - ollama
